### DISCUSSION TITLE
Addressing Viewport Challenges in Web Components

### DISCUSSION THREAD

**Discussion by thejfreitas** [justeattakeaway/pie#1307] [Ideas]
I am reaching out to discuss a challenge we've encountered in our Web Components projects related to viewport handling, particularly when dealing with components that exhibit different formats on narrow screens.

In the Pie Notification component we have the option to stack action buttons, however the design docs say to allow stacking these buttons only on narrow screens: https://www.figma.com/file/pPSC73rPin4csb8DiK1CRr/branch/r96WaDE105zDbe5itnleVv/%E2%9C%A8-%5BCore%5D-Web-Components-%5BPIE-3%5D?node-id=3119%3A77568&mode=dev

In the moment that I wrote this topic in our codebase I saw that we have some `mixins` coming from `foozie` but these are only available on `pie-docs`.
```scss
@include f.media('>=wide') {
        grid-template: var(--header-height) 1fr max-content / var(--sidenav-width-wide) 1fr;
        grid-template-areas:
            'header header'
            'nav main'
            'nav footer';
    }
```
Also in the web components we already have some using viewports but with different breakpoints:
![Screenshot 2024-02-26 at 11 45 13 AM](https://github.com/justeattakeaway/pie/assets/7768202/1a256fec-768d-488d-be4e-22f1ff2d6fb3)

I was wondering if we could think of a solution to set proper viewports values  so then we can create util functions/mixins to standardise breakpoints and guarantee consistency on different  design requirements.

I like the values defined by Tailwind CSS for their viewports, it might be a nice inspiration if we all agree to build some kind of util function set: https://tailwindcss.com/docs/responsive-design
Also I liked how `foozie` implements these mixins and I think this is a very clever way to handle this.

Share your thoughts! Have you faced similar challenges, and how did you handle them?
